sonar.projectKey=25.1_DotNetFramework:master
sonar.projectName=25.1_DotNetFramework
sonar.projectVersion=1.0
sonar.working.directory=D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\Trainingcontents\\Newfolder
sonar.sources=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\packages\\MSTest.TestAdapter.1.2.0\\build\\_common\\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\packages\\MSTest.TestAdapter.1.2.0\\build\\_common\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\packages\\MSTest.TestAdapter.1.2.0\\build\\_common\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll"

12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.projectKey=25.1_DotNetFramework:master:12EC86AA-5CC3-426C-92E1-55EE2D22266B
12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.projectName=WebApplication1
12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.projectBaseDir=D:\\Trainingcontents\\Newfolder\\WebApplication1
12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.sourceEncoding=utf-8
12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.sources=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\App_Start\\BundleConfig.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\App_Start\\FilterConfig.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\App_Start\\RouteConfig.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Controllers\\HomeController.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Global.asax.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Properties\\AssemblyInfo.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap-theme.css",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap-theme.min.css",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap.css",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap.min.css",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\favicon.ico",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\fonts\\glyphicons-halflings-regular.svg",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Global.asax",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\Site.css",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\bootstrap.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\bootstrap.min.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.min.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.slim.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.slim.min.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery.validate.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery.validate.min.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery.validate.unobtrusive.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery.validate.unobtrusive.min.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\modernizr-2.8.3.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Web.config",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Web.Debug.config",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Web.Release.config",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Web.config",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\_ViewStart.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Shared\\Error.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Shared\\_Layout.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Home\\About.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Home\\Contact.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Views\\Home\\Index.cshtml",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\fonts\\glyphicons-halflings-regular.woff2",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\fonts\\glyphicons-halflings-regular.woff",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\fonts\\glyphicons-halflings-regular.ttf",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\fonts\\glyphicons-halflings-regular.eot",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap.min.css.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap.css.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap-theme.min.css.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Content\\bootstrap-theme.css.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.slim.min.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.min.map",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery-3.4.1.intellisense.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\Scripts\\jquery.validate-vsdoc.js",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\packages.config"

12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.cs.analyzer.projectOutPaths=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\0"
12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.cs.roslyn.reportFilePaths=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\0\\Issues.json"

12EC86AA-5CC3-426C-92E1-55EE2D22266B.sonar.working.directory=D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\.sonar\\mod0
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.projectKey=25.1_DotNetFramework:master:189AF127-602A-47D6-9E70-55FAB91979D6
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.projectName=WebApplication1.Tests
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.projectBaseDir=D:\\Trainingcontents\\Newfolder\\WebApplication1.Tests
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.sourceEncoding=utf-8
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.sources=
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.tests=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1.Tests\\Properties\\AssemblyInfo.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1.Tests\\Controllers\\HomeControllerTest.cs",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1.Tests\\App.config",\
"D:\\Trainingcontents\\Newfolder\\WebApplication1.Tests\\packages.config"

189AF127-602A-47D6-9E70-55FAB91979D6.sonar.cs.analyzer.projectOutPaths=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\1"
189AF127-602A-47D6-9E70-55FAB91979D6.sonar.cs.roslyn.reportFilePaths=\
"D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\1\\Issues.json"

189AF127-602A-47D6-9E70-55FAB91979D6.sonar.working.directory=D:\\Trainingcontents\\Newfolder\\WebApplication1\\.sonarqube\\out\\.sonar\\mod1
sonar.branch.name=Dev
sonar.host.url=http://172.27.59.174:9000/
sonar.visualstudio.enable=false

sonar.modules=12EC86AA-5CC3-426C-92E1-55EE2D22266B,189AF127-602A-47D6-9E70-55FAB91979D6

